version: '3.8'
services:
  rustfs:
    image: rustfs/rustfs
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    volumes:
      - ./rustfs/data:/data
      - ./etc/localtime:/etc/localtime:ro
